### ISSUE TITLE
Variable naming in solutions/3/2_clock_itertools.py is ... suboptimal

### ISSUE THREAD

**Issue by mathiasbockwoldt** [uit-no/python-open-mike#7]
In solution `solutions/3/2_clock_itertools.py`, the variable naming is not intuitive. The meaning of the variables  `m`, `_m`, `t`, and `_t` are not clear at all. Unless you used these names deliberately to show bad names, it might be good to use more meaningful names.

**Comment by bast** [comment]
Very valid point :-). Fix coming up.
